version: '3.3'
services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8077:80'
        environment:
            - PMA_HOST=db

    db:
        image: mysql:latest
        ports:
            - '5506:3306'
        restart: unless-stopped
        environment:
            MYSQL_USER: user_laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: social_hub_manager

